# -*- coding: utf-8 -*-
"""My copx of Waveglow.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12yoGkOrXzrGiQ74lnKE-Onx-0avOEfAx
"""

import os

!git clone https://github.com/haukedau/waveglow
os.chdir('waveglow')
!git submodule init
!git submodule update

!pip3 install -r tacotron2/requirements.txt

!pip3 install -r requirements.txt

!wget "http://www.myown-it.de/waveglow_old.pt" -O "waveglow_old.pt"

!wget "http://www.myown-it.de/mel_spectrograms.zip" -O "mel_spectrograms.zip"

!unzip mel_spectrograms.zip

!python inference.py -f mel_files.txt -w waveglow_old.pt  -o ./outputSound --is_fp16 -s 0.6

import IPython.display as ipd

ipd.Audio('LJ001-0015.wav_synthesis.wav')

